### ISSUE TITLE
Interested in Python3 compatibility?

### ISSUE THREAD

**Issue by jsivak** [elifiner/pydump#2]
Howdy,

Found pydump today and have been making changes to make it work in Python3 only.

Are you interested in updates to this script (given its been "idle" for so long)?

If so, then I think I'd try to use ``six`` to try to make this Python2/3 compatible. If not, then I'll just keep my Python3 version.

Thanks

**Comment by finereli** [comment]
Absolutely! I was really excited about pydump when I wrote it and it really helped me at a job I had at the time, but never got any traction for anybody else to use it. I'm happy you've stumbled on it and yeah, Python 3 support will be very nice.

**Comment by jsivak** [comment]
Are you looking for a Python 2 and 3 compatible version?  I have the Python 3 "only" changes on a branch already.

**Comment by finereli** [comment]
It would be better to have support for both, but I think Python 2 is slowly (finally) dying out.
We can keep the Python 2 code in a branch and put your modifications in master.
How does that sound?

**Comment by jsivak** [comment]
I'm pretty busy at work now, but I'd be curious to try and use the "six" package to try and keep support for both Python 2 and 3, but I won't have time to try this until August.

**Comment by finereli** [comment]
Python 3 is fully supported now.

**Comment by jsivak** [comment]
Excellent! Thanks for the update!
